"""
INTERNAL - Fashionpedia YOLO class/keyword maps imported by data_prep/segment.py. Not run directly.

Keyword mappings for Fashionpedia YOLO11 segmentation model.

Model: Fashionpedia_YOLO11l_241114/best.pt
Dataset: Fashionpedia
Created: 2024-11-14

These mappings connect product title keywords (e.g., "hoodie", "joggers") to
Fashionpedia dataset class names (e.g., "top, t-shirt, sweatshirt, shirt, blouse").

When YOLO detects garment classes, the script uses these mappings to verify that
detected classes match the product type mentioned in the title. This filtering
ensures we're segmenting the correct garment from multi-item product images.

Usage:
    from data_prep.keyword_maps import BRAND_KEYWORD_MAPS
    keywordmap = BRAND_KEYWORD_MAPS["nike"]
"""

BRAND_KEYWORD_MAPS = {
    "nike": {
        't-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'top': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tee': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tees': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'hoodie': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crew': 'top, t-shirt, sweatshirt, shirt, blouse',
        'polo': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tank': 'top, t-shirt, sweatshirt, shirt, blouse',
        'henley': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweater': 'sweater',
        'pullover': 'sweater',
        'shacket': 'sweater',
        'half-zip': 'sweater',
        'cardigan': 'cardigan',
        'jacket': 'jacket',
        'puffer': 'jacket',
        'bomber': 'jacket',
        'parka': 'jacket',
        'anorak': 'jacket',
        'poncho': 'jacket',
        'vest': 'vest',
        'pants': 'pants',
        'pant': 'pants',
        'joggers': 'pants',
        'jogger': 'pants',
        'trousers': 'pants',
        'overalls': 'pants',
        'shorts': 'shorts',
        'short': 'shorts',
        'skirt': 'skirt',
        'skort': 'skirt',
        'coat': 'coat',
        'trench': 'coat',
        'dress': 'dress',
        'hat': 'hat',
        'cap': 'hat',
        'beanie': 'hat',
        'visor': 'hat',
        'tights': 'tights, stockings',
        'legging': 'tights, stockings',
        'shoes': 'shoe',
        'slides': 'shoe',
        'slide': 'shoe',
        'cleats': 'shoe',
        'spikes': 'shoe',
        'boots': 'shoe',
        'bag': 'bag, wallet',
        'backpack': 'bag, wallet',
        'tote': 'bag, wallet',
        'wallet': 'bag, wallet',
        'sock': 'sock',
        'socks': 'sock',
        'head tie': 'headband, head covering, hair accessory',
        'jumpsuit': 'jumpsuit',
        'tracksuit': 'jumpsuit',
        'singlet': 'top, t-shirt, sweatshirt, shirt, blouse',
        'mock': 'top, t-shirt, sweatshirt, shirt, blouse',
        'skate-t-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatpants': 'pants'
    },

    "adidas": {
        't-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'top': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tee': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tees': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'hoodie': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crew': 'top, t-shirt, sweatshirt, shirt, blouse',
        'polo': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tank': 'top, t-shirt, sweatshirt, shirt, blouse',
        'henley': 'top, t-shirt, sweatshirt, shirt, blouse',
        'jersey': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweater': 'sweater',
        'pullover': 'sweater',
        'shacket': 'sweater',
        'half-zip': 'sweater',
        'cardigan': 'cardigan',
        'jacket': 'jacket',
        'puffer': 'jacket',
        'bomber': 'jacket',
        'parka': 'jacket',
        'anorak': 'jacket',
        'poncho': 'jacket',
        'vest': 'vest',
        'pants': 'pants',
        'pant': 'pants',
        'joggers': 'pants',
        'jogger': 'pants',
        'trousers': 'pants',
        'overalls': 'pants',
        'shorts': 'shorts',
        'short': 'shorts',
        'skirt': 'skirt',
        'skort': 'skirt',
        'coat': 'coat',
        'trench': 'coat',
        'dress': 'dress',
        'hat': 'hat',
        'cap': 'hat',
        'beanie': 'hat',
        'visor': 'hat',
        'tights': 'tights, stockings',
        'legging': 'tights, stockings',
        'leggings': 'tights, stockings',
        'shoes': 'shoe',
        'slides': 'shoe',
        'slide': 'shoe',
        'cleats': 'shoe',
        'spikes': 'shoe',
        'boots': 'shoe',
        'bag': 'bag, wallet',
        'backpack': 'bag, wallet',
        'tote': 'bag, wallet',
        'wallet': 'bag, wallet',
        'sock': 'sock',
        'socks': 'sock',
        'head tie': 'headband, head covering, hair accessory',
        'jumpsuit': 'jumpsuit',
        'tracksuit': 'jumpsuit',
        'bodysuit': 'jumpsuit',
        'kit': 'jumpsuit',
        'singlet': 'top, t-shirt, sweatshirt, shirt, blouse',
        'mock': 'top, t-shirt, sweatshirt, shirt, blouse',
        'skate-t-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatpants': 'pants'
    },

    "puma": {
        't-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'top': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tee': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tees': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'hoodie': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crew': 'top, t-shirt, sweatshirt, shirt, blouse',
        'polo': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tank': 'top, t-shirt, sweatshirt, shirt, blouse',
        'henley': 'top, t-shirt, sweatshirt, shirt, blouse',
        'jersey': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweater': 'sweater',
        'pullover': 'sweater',
        'shacket': 'sweater',
        'half-zip': 'sweater',
        'cardigan': 'cardigan',
        'jacket': 'jacket',
        'puffer': 'jacket',
        'bomber': 'jacket',
        'parka': 'jacket',
        'anorak': 'jacket',
        'poncho': 'jacket',
        'vest': 'vest',
        'pants': 'pants',
        'pant': 'pants',
        'joggers': 'pants',
        'jogger': 'pants',
        'trousers': 'pants',
        'overalls': 'pants',
        'shorts': 'shorts',
        'short': 'shorts',
        'skirt': 'skirt',
        'skort': 'skirt',
        'coat': 'coat',
        'trench': 'coat',
        'dress': 'dress',
        'hat': 'hat',
        'cap': 'hat',
        'beanie': 'hat',
        'visor': 'hat',
        'tights': 'tights, stockings',
        'legging': 'tights, stockings',
        'leggings': 'tights, stockings',
        'shoes': 'shoe',
        'slides': 'shoe',
        'slide': 'shoe',
        'cleats': 'shoe',
        'spikes': 'shoe',
        'boots': 'shoe',
        'sneakers': 'shoe',
        'bag': 'bag, wallet',
        'backpack': 'bag, wallet',
        'tote': 'bag, wallet',
        'wallet': 'bag, wallet',
        'sock': 'sock',
        'socks': 'sock',
        'head tie': 'headband, head covering, hair accessory',
        'jumpsuit': 'jumpsuit',
        'tracksuit': 'jumpsuit',
        'bodysuit': 'jumpsuit',
        'kit': 'jumpsuit',
        'singlet': 'top, t-shirt, sweatshirt, shirt, blouse',
        'mock': 'top, t-shirt, sweatshirt, shirt, blouse',
        'skate-t-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatpants': 'pants'
    },

    "lulu": {
        't-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'top': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tee': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tees': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'hoodie': 'top, t-shirt, sweatshirt, shirt, blouse',
        'full zip': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crew': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crop': 'top, t-shirt, sweatshirt, shirt, blouse',
        'polo': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tank': 'top, t-shirt, sweatshirt, shirt, blouse',
        'henley': 'top, t-shirt, sweatshirt, shirt, blouse',
        'jersey': 'top, t-shirt, sweatshirt, shirt, blouse',
        'overshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'turtleneck': 'top, t-shirt, sweatshirt, shirt, blouse',
        'button-up': 'top, t-shirt, sweatshirt, shirt, blouse',
        'baselayer': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweater': 'sweater',
        'pullover': 'sweater',
        'shacket': 'sweater',
        'half-zip': 'sweater',
        'half-zip': 'sweater',
        'cardigan': 'cardigan',
        'jacket': 'jacket',
        'puffer': 'jacket',
        'bomber': 'jacket',
        'parka': 'jacket',
        'anorak': 'jacket',
        'poncho': 'jacket',
        'windbreaker': 'jacket',
        'vest': 'vest',
        'pants': 'pants',
        'pant': 'pants',
        'joggers': 'pants',
        'jogger': 'pants',
        'trousers': 'pants',
        'trouser': 'pants',
        'overalls': 'pants',
        'shorts': 'shorts',
        'short': 'shorts',
        'skirt': 'skirt',
        'skort': 'skirt',
        'coat': 'coat',
        'trench': 'coat',
        'dress': 'dress',
        'hat': 'hat',
        'cap': 'hat',
        'beanie': 'hat',
        'visor': 'hat',
        'tights': 'tights, stockings',
        'legging': 'tights, stockings',
        'leggings': 'tights, stockings',
        'shoes': 'shoe',
        'slides': 'shoe',
        'slide': 'shoe',
        'cleats': 'shoe',
        'spikes': 'shoe',
        'boots': 'shoe',
        'sneakers': 'shoe',
        'bag': 'bag, wallet',
        'backpack': 'bag, wallet',
        'tote': 'bag, wallet',
        'wallet': 'bag, wallet',
        'pouch': 'bag, wallet',
        'sock': 'sock',
        'socks': 'sock',
        'head tie': 'headband, head covering, hair accessory',
        'headband': 'headband, head covering, hair accessory',
        'headbands': 'headband, head covering, hair accessory',
        'jumpsuit': 'jumpsuit',
        'tracksuit': 'jumpsuit',
        'bodysuit': 'jumpsuit',
        'kit': 'jumpsuit',
        'singlet': 'top, t-shirt, sweatshirt, shirt, blouse',
        'mock': 'top, t-shirt, sweatshirt, shirt, blouse',
        'skate-t-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatpants': 'pants'
    },

    "ua": {
        't-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'top': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tee': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tees': 'top, t-shirt, sweatshirt, shirt, blouse',
        'T': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweatshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'hoodie': 'top, t-shirt, sweatshirt, shirt, blouse',
        'full zip': 'top, t-shirt, sweatshirt, shirt, blouse',
        'full-zip': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crew': 'top, t-shirt, sweatshirt, shirt, blouse',
        'crop': 'top, t-shirt, sweatshirt, shirt, blouse',
        'polo': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tank': 'top, t-shirt, sweatshirt, shirt, blouse',
        'henley': 'top, t-shirt, sweatshirt, shirt, blouse',
        'jersey': 'top, t-shirt, sweatshirt, shirt, blouse',
        'overshirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'turtleneck': 'top, t-shirt, sweatshirt, shirt, blouse',
        'button-up': 'top, t-shirt, sweatshirt, shirt, blouse',
        'button up': 'top, t-shirt, sweatshirt, shirt, blouse',
        'baselayer': 'top, t-shirt, sweatshirt, shirt, blouse',
        'midlayer': 'top, t-shirt, sweatshirt, shirt, blouse',
        'long sleeve': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sleeveless': 'top, t-shirt, sweatshirt, shirt, blouse',
        'v-neck': 'top, t-shirt, sweatshirt, shirt, blouse',
        'flannel': 'top, t-shirt, sweatshirt, shirt, blouse',
        'raglan': 'top, t-shirt, sweatshirt, shirt, blouse',
        'singlet': 'top, t-shirt, sweatshirt, shirt, blouse',
        'mock': 'top, t-shirt, sweatshirt, shirt, blouse',
        'skate-t-shirt': 'top, t-shirt, sweatshirt, shirt, blouse',
        'tunic': 'top, t-shirt, sweatshirt, shirt, blouse',
        'sweater': 'sweater',
        'pullover': 'sweater',
        'shacket': 'sweater',
        'half-zip': 'sweater',
        'half-zip': 'sweater',
        'cardigan': 'cardigan',
        'jacket': 'jacket',
        'puffer': 'jacket',
        'bomber': 'jacket',
        'parka': 'jacket',
        'anorak': 'jacket',
        'poncho': 'jacket',
        'swacket': 'jacket',
        'windbreaker': 'jacket',
        'vest': 'vest',
        'pants': 'pants',
        'pant': 'pants',
        'joggers': 'pants',
        'jogger': 'pants',
        'trousers': 'pants',
        'trouser': 'pants',
        'overalls': 'pants',
        'capris': 'pants',
        'capri': 'pants',
        'shorts': 'shorts',
        'short': 'shorts',
        'shorty': 'shorts',
        'skirt': 'skirt',
        'skort': 'skirt',
        'sportskort': 'skirt',
        'coat': 'coat',
        'trench': 'coat',
        'dress': 'dress',
        'hat': 'hat',
        'cap': 'hat',
        'beanie': 'hat',
        'visor': 'hat',
        'tights': 'tights, stockings',
        'legging': 'tights, stockings',
        'leggings': 'tights, stockings',
        'shoes': 'shoe',
        'slides': 'shoe',
        'slide': 'shoe',
        'slider': 'shoe',
        'cleats': 'shoe',
        'spikes': 'shoe',
        'boots': 'shoe',
        'sneakers': 'shoe',
        'bag': 'bag, wallet',
        'backpack': 'bag, wallet',
        'tote': 'bag, wallet',
        'wallet': 'bag, wallet',
        'pouch': 'bag, wallet',
        'crossbody': 'bag, wallet',
        'duffle': 'bag, wallet',
        'sling': 'bag, wallet',
        'sackpack': 'bag, wallet',
        'sack': 'bag, wallet',
        'sock': 'sock',
        'socks': 'sock',
        'head tie': 'headband, head covering, hair accessory',
        'headband': 'headband, head covering, hair accessory',
        'headbands': 'headband, head covering, hair accessory',
        'jumpsuit': 'jumpsuit',
        'tracksuit': 'jumpsuit',
        'bodysuit': 'jumpsuit',
        'kit': 'jumpsuit',
        'jumper': 'jumpsuit',
        'runsie': 'jumpsuit',
        'sweatpants': 'pants'
    }
}
